# This is a basic workflow to help you get started with Actions

name: LLVM

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  create:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Get Clang's version
        run: clang --version

      - name: Check our path
        run: pwd
      - name: Extracting llc's host target
        run: llc-9 --version | grep CPU
      - name: Compile test tool, for retrieveing CPU features
        run: clang -I/usr/lib/llvm-9/include/ -I/usr/lib/llvm-9/include/llvm-c -L/usr/lib/llvm-9/lib -lLLVM-9 -lstdc++ $GITHUB_WORKSPACE/llvm_cpu_features_investigation.cpp

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          which llc-9
          llc-9
